# 🚀 Docker setup (Not in use yet, planned for deployment)
version: '3.8'

services:
  web:
    build: ./apps/web
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./apps/web:/app
      - /app/node_modules

  api:
    build: ./apps/api
    ports:
      - '4000:4000'
    env_file:
      - .env
    volumes:
      - ./apps/api:/app
      - /app/node_modules

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doceditor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
